# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:45:51+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Penalty(BaseModel):
    BenchPenaltyServedByPlayerID: Optional[int] = None
    Description: Optional[str] = None
    DrawnByPlayerID: Optional[int] = None
    DrawnByTeamID: Optional[int] = None
    IsBenchPenalty: Optional[bool] = None
    PenalizedPlayerID: Optional[int] = None
    PenalizedTeamID: Optional[int] = None
    PenaltyID: Optional[int] = None
    PenaltyMinutes: Optional[int] = None
    PeriodID: Optional[int] = None
    Sequence: Optional[int] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None


class Play(BaseModel):
    AwayTeamScore: Optional[int] = None
    Category: Optional[str] = None
    ClockMinutes: Optional[int] = None
    ClockSeconds: Optional[int] = None
    Created: Optional[str] = None
    Description: Optional[str] = None
    FirstAssistedByPlayerID: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpposingPlayerID: Optional[int] = None
    PeriodID: Optional[int] = None
    PeriodName: Optional[str] = None
    PlayID: Optional[int] = None
    PlayerID: Optional[int] = None
    PowerPlayTeam: Optional[str] = None
    PowerPlayTeamID: Optional[int] = None
    SecondAssistedByPlayerID: Optional[int] = None
    Sequence: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Type: Optional[str] = None
    Updated: Optional[str] = None


class ScoringPlay(BaseModel):
    AllowedByTeamID: Optional[int] = None
    AssistedByPlayerID1: Optional[int] = None
    AssistedByPlayerID2: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    EmptyNet: Optional[bool] = None
    HomeTeamScore: Optional[int] = None
    PeriodID: Optional[int] = None
    PowerPlay: Optional[bool] = None
    ScoredByPlayerID: Optional[int] = None
    ScoredByTeamID: Optional[int] = None
    ScoringPlayID: Optional[int] = None
    Sequence: Optional[int] = None
    ShortHanded: Optional[bool] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None


class Series(BaseModel):
    AwayTeamWins: Optional[int] = None
    GameNumber: Optional[int] = None
    HomeTeamWins: Optional[int] = None
    MaxLength: Optional[int] = None


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class Period(BaseModel):
    AwayScore: Optional[int] = None
    GameID: Optional[int] = None
    HomeScore: Optional[int] = None
    Name: Optional[str] = None
    Penalties: Optional[List[Penalty]] = None
    PeriodID: Optional[int] = None
    ScoringPlays: Optional[List[ScoringPlay]] = None


class Game(BaseModel):
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    Channel: Optional[str] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    IsClosed: Optional[bool] = None
    LastPlay: Optional[str] = None
    NeutralVenue: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    Period: Optional[str] = None
    Periods: Optional[List[Period]] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SeriesInfo: Optional[Series] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None


class PlayByPlay(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    Plays: Optional[List[Play]] = None


class FieldFormatPlayByPlayDeltaDateMinutesGetResponse(RootModel[List[PlayByPlay]]):
    root: List[PlayByPlay]
